=== Goddard/NearInfinity/src/org/infinity/updater/update_v2.dtd
<!ELEMENT update (general?, release+)>
<!ATTLIST update version CDATA #REQUIRED>

<!ELEMENT general (server*, info*)>

<!ELEMENT release (github, file?, changelog?)>
<!ATTLIST release type (latest|stable|updater) "latest">

<!ELEMENT server (link)>

<!ELEMENT info (name, link)>

<!ELEMENT name (#PCDATA)>

<!ELEMENT link (#PCDATA)>

<!ELEMENT github (url+)>

<!ELEMENT file (name, url, version, timestamp, hash, link)>

<!ELEMENT changelog (entry+)>

<!ELEMENT url (#PCDATA)>
<!ATTLIST url type (json|xml|jar|zip|gzip) #REQUIRED>

<!ELEMENT type (#PCDATA)>

<!ELEMENT version (#PCDATA)>

<!ELEMENT timestamp (#PCDATA)>

<!ELEMENT hash (#PCDATA)>

<!ELEMENT entry (#PCDATA)>

=== Goddard/NearInfinity/src/org/infinity/updater/update-template.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE update SYSTEM "update_v2.dtd">

<!--
The file "update.xml" provides all the required information about available files involved in the 
update process of Near Infinity.
This template provides a basic example of how to set up this file correctly.
Text content is always considered case-sensitive. Attribute values can be of any case.
Whitespace around text content will be trimmed automatically.
-->

<!-- Root element "update". Version attribute will be used to distinguish between different 
     revisions of the update.xml specification. A version change will usually require an updated 
     DOCTYPE reference. New update versions are supposed to be backwards compatible. -->
<update version="2">
  <!-- This section provides general NearInfinity-related information. (optional) -->
  <general>
    <!-- Server elements provide information about alternative update server. You can specify 
         as many as needed. (optional) -->
    <server>
      <!-- The URL to an alternative server. (mandatory) -->
      <link>https://github.com/NearInfinityBrowser/NearInfinity/</link>
    </server>
    <!-- Info elements provide links to related websites. You can specify as many as needed. (optional) -->
    <info>
      <!-- A name or label for the provided link. (mandatory) -->
      <name>Near Infinity on SHS Forums</name>
      <!-- A URL to a releated website. (mandatory) -->
      <link>http://www.shsforums.net/topic/45358-nearinfinity/</link>
    </info>
    <info>
      <name>Near Infinity on Baldur's Gate Forums</name>
      <link>http://forum.baldursgate.com/discussion/30593/new-versions-of-nearinfinity-available/</link>
    </info>
  </general>

  <!-- "release" section is mandatory and defines specific Near Infinity releases that can be used
       to update an older version.
       At least one release section has to be present. Supported types: latest, stable, updater. -->
  <release type="stable">
    <!-- This mandatory element was introduced by version 2 of the update.xml specification.
         It is the new source of information to detect whether a new release is available. -->
    <github>
      <!-- Points to JSON data with release information. -->
      <url type="json">https://api.github.com/repos/Argent77/NearInfinity/releases/latest</url>
      <url type="json">https://api.github.com/repos/Argent77/NearInfinity/releases/tags/v2.3-20230303</url>
    </github>
    <!-- The (now optional) file element is deprecated since version 2 and exists only for compatibility 
         with older Near Infinity versions.
         In the past it contained all information of a specific file needed for the update process.
         It is recommended to keep information about the first release supporting version 2 of update.xml. -->
    <file>
      <!-- "name" specifies the actual filename. (mandatory) -->
      <name>NearInfinity.jar</name>
      <!-- "url" specifies the URL which is used to download the file of specified "type" which is 
            either jar, zip or gzip. (mandatory) -->
      <url type="zip">https://github.com/Argent77/NearInfinity/releases/download/v2.3-20230303/NearInfinity-20230303.zip</url>
      <!-- "version" specifies the version of the file. (mandatory) -->
      <version>v2.3-20230303</version>
      <!-- "timestamp" defines the release date and time of the file in ISO 8601 format. (mandatory) -->
      <timestamp>2023-03-03T19:12+01:00</timestamp>
      <!-- "hash" specifies the md5 checksum/hash value of the file. (mandatory) -->
      <hash>221aec49b1710ae92876e22f0cd3d2d8</hash>
      <!-- "link" specifies a URL which can be used to manually download the file. (mandatory) -->
      <link>https://github.com/Argent77/NearInfinity/releases/tag/v2.3-20230303</link>
    </file>
    <!-- "changelog" contains changes introduced in the current release. (optional) -->
    <changelog>
      <!-- One or more changelog entries. Each entry will be displayed as a separate list 
           element. (mandatory) -->
      <entry>Added feature X.</entry>
      <entry>Fixed missing fields in XYZ V1.0 resources.</entry>
    </changelog>
  </release>
</update>
